---
# tasks file for apache

- name: install apache
  yum:
    name: "{{ httpd_package }}"
    state: latest

- name: start and enable apache
  service:
    name: "{{ httpd_service }}"
    state: started
    enabled: true
