---
- name: Import in-memory inventory play
  import_playbook: in-memory-inventory.yml

- name: configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - {name: repos, tags: base-config}

- name: deploy haproxy
  hosts: frontends
  gather_facts: true
  become: true
  roles:
    - {name: haproxy, tags: [lbs, haproxy]}

- name: deploy tomcat
  hosts: apps
  gather_facts: true
  become: true
  roles:
    - {name: tomcat, tags: [apps, tomcat]}

- name: deploy postgres
  hosts: appdbs
  gather_facts: true
  become: true
  roles:
    - {name: postgres, tags: [dbs, postgres]}
