---
- name: configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - repos

- name: deploy haproxy
  hosts: frontends
  gather_facts: true
  become: true
  roles:
    - haproxy

- name: deploy tomcat
  hosts: apps
  gather_facts: true
  become: true
  roles:
    - tomcat
    - apache

- name: deploy postgres
  hosts: appdbs
  gather_facts: true
  become: true
  roles:
    - postgres
